### ISSUE TITLE
Latest update with this error issue please help

### ISSUE THREAD

**Issue by anotherpop** [guoyww/AnimateDiff#282]
Latest update with this error issue please help.

*** Error running process: D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 718, in process
        script.process(p, *script_args)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1138, in process
        self.controlnet_hack(p)
      File "D:\stable-diffusion-webui\extensions\sd-webui-controlnet\scripts\controlnet.py", line 1123, in controlnet_hack
        self.controlnet_main_entry(p)
      File "D:\stable-diffusion-webui\extensions\sd-webui-animatediff\scripts\animatediff_cn.py", line 248, in hacked_main_entry
        model_net.reset()
    AttributeError: 'ControlModel' object has no attribute 'reset'

---

**Comment by MrSassyGit** [comment]
I have the exact same issue. New Automatic1111 install, only Animatediff and Controlnet extension installed. Both animatediff and controlnet work fine independently but not together. Error shows but the video still renders but with no controlnet effect.
4070Ti Super with latest drivers
Looking into solutions now, hope someone can help!

**Comment by nitinmukesh** [comment]
Same error. No solution

**Comment by fulleclip** [comment]
same mistake for me

**Comment by davidmartinrius** [comment]
same error here... but I did not find any solution yet

**Comment by fulleclip** [comment]
I just installed an update [2573b2b5] but I still get the same error

**Comment by davidmartinrius** [comment]
The only thing that worked for me is to go to an older CN branch. Explained here:
https://github.com/continue-revolution/sd-webui-animatediff/issues/412#issuecomment-1913429785

**Comment by Danny-707** [comment]
> The only thing that worked for me is to go to an older CN branch. Explained here: [continue-revolution/sd-webui-animatediff#412 (comment)](https://github.com/continue-revolution/sd-webui-animatediff/issues/412#issuecomment-1913429785)

Thank you for the link!
Could you please describe in a bit more detail what steps need to be taken?
It says 'Navigate to extensions/sd-webui-controlnet in terminal', but I'm not sure which terminal it refers to.

**Comment by protector131090** [comment]
still no fix

**Comment by morozig** [comment]
Actually after updating animatediff to latest everything started working.
